package co.roomapp.room.model;

import android.database.sqlite.SQLiteDatabase;

import java.io.Serializable;
import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import co.roomapp.room.model.RAAttachment;
import co.roomapp.room.model.RABlockMember;
import co.roomapp.room.model.RAChatSession;
import co.roomapp.room.model.RAContact;
import co.roomapp.room.model.RAContactSection;
import co.roomapp.room.model.RAMessage;
import co.roomapp.room.model.RANotification;
import co.roomapp.room.model.RAPhone;
import co.roomapp.room.model.RARoomInvite;
import co.roomapp.room.model.RARoom;

import co.roomapp.room.model.RAAttachmentDao;
import co.roomapp.room.model.RABlockMemberDao;
import co.roomapp.room.model.RAChatSessionDao;
import co.roomapp.room.model.RAContactDao;
import co.roomapp.room.model.RAContactSectionDao;
import co.roomapp.room.model.RAMessageDao;
import co.roomapp.room.model.RANotificationDao;
import co.roomapp.room.model.RAPhoneDao;
import co.roomapp.room.model.RARoomInviteDao;
import co.roomapp.room.model.RARoomDao;
import co.roomapp.room.model.RAMemberDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession implements Serializable{

    private final DaoConfig rAAttachmentDaoConfig;
    private final DaoConfig rABlockMemberDaoConfig;
    private final DaoConfig rAChatSessionDaoConfig;
    private final DaoConfig rAContactDaoConfig;
    private final DaoConfig rAContactSectionDaoConfig;
    private final DaoConfig rAMessageDaoConfig;
    private final DaoConfig rANotificationDaoConfig;
    private final DaoConfig rAPhoneDaoConfig;
    private final DaoConfig rARoomInviteDaoConfig;
    private final DaoConfig rARoomDaoConfig;
    private final DaoConfig rAMemberDaoConfig;

    private final RAAttachmentDao rAAttachmentDao;
    private final RABlockMemberDao rABlockMemberDao;
    private final RAChatSessionDao rAChatSessionDao;
    private final RAContactDao rAContactDao;
    private final RAContactSectionDao rAContactSectionDao;
    private final RAMessageDao rAMessageDao;
    private final RANotificationDao rANotificationDao;
    private final RAPhoneDao rAPhoneDao;
    private final RARoomInviteDao rARoomInviteDao;
    private final RARoomDao rARoomDao;
    private final RAMemberDao rAMemberDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        rAAttachmentDaoConfig = daoConfigMap.get(RAAttachmentDao.class).clone();
        rAAttachmentDaoConfig.initIdentityScope(type);

        rABlockMemberDaoConfig = daoConfigMap.get(RABlockMemberDao.class).clone();
        rABlockMemberDaoConfig.initIdentityScope(type);

        rAChatSessionDaoConfig = daoConfigMap.get(RAChatSessionDao.class).clone();
        rAChatSessionDaoConfig.initIdentityScope(type);

        rAContactDaoConfig = daoConfigMap.get(RAContactDao.class).clone();
        rAContactDaoConfig.initIdentityScope(type);

        rAContactSectionDaoConfig = daoConfigMap.get(RAContactSectionDao.class).clone();
        rAContactSectionDaoConfig.initIdentityScope(type);

        rAMessageDaoConfig = daoConfigMap.get(RAMessageDao.class).clone();
        rAMessageDaoConfig.initIdentityScope(type);

        rANotificationDaoConfig = daoConfigMap.get(RANotificationDao.class).clone();
        rANotificationDaoConfig.initIdentityScope(type);

        rAPhoneDaoConfig = daoConfigMap.get(RAPhoneDao.class).clone();
        rAPhoneDaoConfig.initIdentityScope(type);

        rARoomInviteDaoConfig = daoConfigMap.get(RARoomInviteDao.class).clone();
        rARoomInviteDaoConfig.initIdentityScope(type);

        rARoomDaoConfig = daoConfigMap.get(RARoomDao.class).clone();
        rARoomDaoConfig.initIdentityScope(type);

        rAMemberDaoConfig = daoConfigMap.get(RAMemberDao.class).clone();
        rAMemberDaoConfig.initIdentityScope(type);

        rAAttachmentDao = new RAAttachmentDao(rAAttachmentDaoConfig, this);
        rABlockMemberDao = new RABlockMemberDao(rABlockMemberDaoConfig, this);
        rAChatSessionDao = new RAChatSessionDao(rAChatSessionDaoConfig, this);
        rAContactDao = new RAContactDao(rAContactDaoConfig, this);
        rAContactSectionDao = new RAContactSectionDao(rAContactSectionDaoConfig, this);
        rAMessageDao = new RAMessageDao(rAMessageDaoConfig, this);
        rANotificationDao = new RANotificationDao(rANotificationDaoConfig, this);
        rAPhoneDao = new RAPhoneDao(rAPhoneDaoConfig, this);
        rARoomInviteDao = new RARoomInviteDao(rARoomInviteDaoConfig, this);
        rARoomDao = new RARoomDao(rARoomDaoConfig, this);
        rAMemberDao = new RAMemberDao(rAMemberDaoConfig, this);

        registerDao(RAAttachment.class, rAAttachmentDao);
        registerDao(RABlockMember.class, rABlockMemberDao);
        registerDao(RAChatSession.class, rAChatSessionDao);
        registerDao(RAContact.class, rAContactDao);
        registerDao(RAContactSection.class, rAContactSectionDao);
        registerDao(RAMessage.class, rAMessageDao);
        registerDao(RANotification.class, rANotificationDao);
        registerDao(RAPhone.class, rAPhoneDao);
        registerDao(RARoomInvite.class, rARoomInviteDao);
        registerDao(RARoom.class, rARoomDao);
        registerDao(RAMember.class, rAMemberDao);

    }
    
    public void clear() {
        rAAttachmentDaoConfig.getIdentityScope().clear();
        rABlockMemberDaoConfig.getIdentityScope().clear();
        rAChatSessionDaoConfig.getIdentityScope().clear();
        rAContactDaoConfig.getIdentityScope().clear();
        rAContactSectionDaoConfig.getIdentityScope().clear();
        rAMessageDaoConfig.getIdentityScope().clear();
        rANotificationDaoConfig.getIdentityScope().clear();
        rAPhoneDaoConfig.getIdentityScope().clear();
        rARoomInviteDaoConfig.getIdentityScope().clear();
        rARoomDaoConfig.getIdentityScope().clear();
        rAMemberDaoConfig.getIdentityScope().clear();
    }

    public RAAttachmentDao getRAAttachmentDao() {
        return rAAttachmentDao;
    }

    public RABlockMemberDao getRABlockMemberDao() {
        return rABlockMemberDao;
    }

    public RAChatSessionDao getRAChatSessionDao() {
        return rAChatSessionDao;
    }

    public RAContactDao getRAContactDao() {
        return rAContactDao;
    }

    public RAContactSectionDao getRAContactSectionDao() {
        return rAContactSectionDao;
    }

    public RAMessageDao getRAMessageDao() {
        return rAMessageDao;
    }

    public RANotificationDao getRANotificationDao() {
        return rANotificationDao;
    }

    public RAPhoneDao getRAPhoneDao() {
        return rAPhoneDao;
    }

    public RARoomInviteDao getRARoomInviteDao() {
        return rARoomInviteDao;
    }

    public RARoomDao getRARoomDao() {
        return rARoomDao;
    }

    public RAMemberDao getRAMemberDao() { return rAMemberDao; }

}
